#cloud-config

packages:
  - pptpd

write_files:
  - content: |
          arnaud pptpd __PASSWORD__ *
    path: /etc/ppp/chap-secrets
  - content: |
          net.ipv4.ip_forward = 1
    path: /etc/sysctl.d/98-ip-forward.conf
  - content: |
          option /etc/ppp/pptpd-options
          localip 10.0.0.1
          remoteip 10.0.0.100-199
    path: /etc/pptpd.conf
  - content: |
          asyncmap 0
          noauth
          crtscts
          lock
          hide-password
          modem
          mtu 1400
          lcp-echo-interval 30
          lcp-echo-failure 4
          noipx
    path: /etc/ppp/options

runcmd:
  - [ 'iptables', '-t', 'nat', '-A', 'POSTROUTING', '-o', 'ens3', '-j', 'MASQUERADE' ]
  - [ 'iptables-save' ]
  - [ 'sysctl', '-p', '/etc/sysctl.d/98-ip-forward.conf' ]
